### ISSUE TITLE
How to turn off evaluating in gin config during training?

### ISSUE THREAD

**Issue by dptam** [google-research/prompt-tuning#106]
Hi, 

## Expected Behavior

I am trying to turn off evaluation during training. I thought the way to do this is to set `train_eval_dataset_cfg=None` and `infer_eval_dataset_cfg=None`. I tried setting this in `configs/run/prompt_finetune.gin` after `include "t5x/configs/runs/finetune.gin"` line with 
```
from t5x import train as t5x_train
t5x_train.train:
  train_eval_dataset_cfg = None
  infer_eval_dataset_cfg = None
```

I also tried several other variants of importing `train`, but none seem to worked. 

## Actual Behavior

The model still does evaluation, and when I checked the value of `train_eval_dataset_cfg` and `infer_eval_dataset_cfg` passed into `train` method in `train.py`, the values are not None, but the original values set in `t5x/configs/runs/finetune.gin` 

## Specifications

- Version: Uses commit `f2e111d5a61a0f82feae7f4838862b92659f27ac`  

Thanks

**Comment by blester125** [comment]
To configure parameters on the main entrypoints (train.train, eval.evaluation, etc.) You need to import `__main__` in the gin file. For example, in this file we set the `init_rng` parameter of the evaluation entrypoint https://github.com/google-research/prompt-tuning/blob/e8f5ebeb230781bf16c2cde22298d803a4e07539/prompt_tuning/configs/runs/prompt_eval.gin#L22

Have you tried this in your config?

```python
import __main__ as t5x_train
t5x_train.train:
  train_eval_dataset_cfg = None
  infer_eval_dataset_cfg = None
```

**Comment by dptam** [comment]
I see. Thank you. It works!
