### ISSUE TITLE
Releasing the pre-trained soft prompts

### ISSUE THREAD

**Issue by d223302** [google-research/prompt-tuning#223]
Hi, thank you for this amazing project and for releasing the codes for reproducing your results. 
The ACL 2022 paper "SPoT: Better Frozen Model Adaptation through Soft Prompt Transfer" says that the soft prompts will be open-sourced to facilitate research in prompt tuning. But it seems that most soft prompts in the paper have not been released in this repo. Are there any places I can find them?
Thanks.

**Comment by blester125** [comment]
Hi!

Thanks for the interest! We are working on getting these released. They will probably be available via a GCP bucket. 

I'm closing this for now but will ping you when they are released!
